/*
 * CRUK-CI Clarity REST API Java Client.
 * Copyright (C) 2013 Cancer Research UK Cambridge Institute.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.01 at 10:52:03 AM GMT
//

package com.genologics.ri.containertype;

import java.io.Serial;
import java.io.Serializable;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 *
 * Dimension is a child element of container type and describes the size and
 * identification method of the horizontal and vertical dimensions of the
 * coordinate system of the container type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimension", propOrder = { "alpha", "offset", "size" })
public class Dimension implements Serializable
{
    /**
     * Class version for serialisation.
     */
    @Serial private static final long serialVersionUID = -1931190014491768673L;

    /**
     * Whether numbering in this dimension is using letters (true) or numbers (false).
     */
    @XmlElement(name = "is-alpha")
    protected Boolean alpha;

    /**
     * The offset applied to the first element in this dimension.
     * For example, an offset of 1 means the first element is numbered/lettered as 1 or B instead of 0 or A.
     */
    protected Integer offset;

    /**
     * The size (number of elements) in this dimension.
     */
    protected Integer size;

    /**
     * Default constructor for creating a new dimension.
     */
    public Dimension()
    {
    }

    /**
     * Constructor for creating a dimension with a specified size.
     *
     * @param size The size (number of elements) in this dimension.
     */
    public Dimension(Integer size)
    {
        this.size = size;
    }

    /**
     * Checks if numbering in this dimension is alphabetic.
     *
     * @return {@code true} if using letters (A, B, C...), {@code false} if using numbers (0, 1, 2...).
     */
    public Boolean isAlpha()
    {
        return alpha;
    }

    /**
     * Sets whether numbering in this dimension is alphabetic.
     *
     * @param alpha {@code true} if using letters (A, B, C...), {@code false} if using numbers (0, 1, 2...).
     */
    public void setAlpha(Boolean alpha)
    {
        this.alpha = alpha;
    }

    /**
     * Gets the offset applied to the first element in this dimension.
     *
     * @return The offset value.
     */
    public Integer getOffset()
    {
        return offset;
    }

    /**
     * Sets the offset applied to the first element in this dimension.
     *
     * @param offset The offset value to set.
     */
    public void setOffset(Integer offset)
    {
        this.offset = offset;
    }

    /**
     * Gets the size (number of elements) in this dimension.
     *
     * @return The size of this dimension.
     */
    public Integer getSize()
    {
        return size;
    }

    /**
     * Sets the size (number of elements) in this dimension.
     *
     * @param size The size to set.
     */
    public void setSize(Integer size)
    {
        this.size = size;
    }

}
